import React, { useState, useEffect } from "react";
import { Pencil, Plus, X, Trash2, MapPin, Check, Upload, Link as LinkIcon, LayoutGrid, Sliders, Share2, Blocks } from "lucide-react";

const KEY = "gamer-profile-page-v2";
const defaults = {
  profile:{name:"Mika Lindqvist",handle:"mikaplays",location:"Gotemburgo, SE",bio:"FPS main. Monto um setup novo todo inverno. Streaming o grind, não os highlights.",avatar:"",banner:""},
  sections:[
    {id:"setup",type:"cards",title:"Setup",items:[{id:"s1",tag:"Periférico",title:"Teclado",detail:"60% hotswap, switches marrons",image:""},{id:"s2",tag:"Periférico",title:"Mouse",detail:"49g wireless, sensor 26k",image:""},{id:"s3",tag:"PC",title:"GPU",detail:"RTX 4080 Super",image:""},{id:"s4",tag:"Monitor",title:"Display",detail:'27" 1440p · 240Hz',image:""}]},
    {id:"games",type:"cards",title:"Jogos favoritos",items:[{id:"g1",tag:"Duelist",title:"Valorant",detail:"Main · Immortal",image:""},{id:"g2",tag:"AWPer",title:"Counter-Strike 2",detail:"Faceit nível 9",image:""},{id:"g3",tag:"BR",title:"Apex Legends",detail:"Diamante",image:""}]},
    {id:"settings",type:"settings",title:"Configurações em jogo",games:["Valorant","Counter-Strike 2"],active:"Valorant",rows:{"Valorant":[["Sensibilidade","0.32"],["DPI","800"],["Crosshair","0;s;1;P;c;5;h;0;f;0;0l;3"]],"Counter-Strike 2":[["Sensibilidade","1.8"],["DPI","800"],["Resolução","1280x960 esticada"]]}},
    {id:"links",type:"links",title:"Redes",items:[{id:"l1",label:"twitch.tv/mikaplays",url:"https://twitch.tv/mikaplays"},{id:"l2",label:"x.com/mikaplays",url:"https://x.com/mikaplays"}]},
    {id:"notes",type:"text",title:"Bastidores",items:[{id:"b1",title:"Tour pela mesa",content:"Walkthrough completo do setup, cabos escondidos e iluminação."}]}
  ]
};
const uid=()=>Math.random().toString(36).slice(2,10);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||defaults}catch{return defaults}}
function ImageBox({value,onChange,round=false}){const [url,setUrl]=useState(false);return <div className={`imgbox ${round?"round":""}`} style={value?{backgroundImage:`url(${value})`}:{}}>{!value&&<span>Imagem</span>}<div className="overlay"><label><Upload size={12}/> Upload<input hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>onChange(r.result);r.readAsDataURL(f)}}/></label><button onClick={()=>{const v=prompt("URL da imagem",value||"");if(v!==null)onChange(v)}}><LinkIcon size={12}/> URL</button>{value&&<button onClick={()=>onChange("")}><Trash2 size={12}/> Remover</button>}</div></div>}
function EditText({value,onChange,tag="span"}){const T=tag;return <T>{value}</T>}
function App(){const [data,setData]=useState(load);const [edit,setEdit]=useState(false);const [picker,setPicker]=useState(false);useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(data))},[data]);const update=(fn)=>setData(d=>fn(structuredClone(d)));
const addSection=t=>update(d=>{d.sections.push({id:uid(),type:t,title:t==="cards"?"Novo bloco":t==="settings"?"Configurações":t==="links"?"Links":"Texto",...(t==="cards"||t==="text"||t==="links"?{items:[]}:{}),...(t==="settings"?{games:[],active:null,rows:{}}:{})});return d});
return <div className="app"><div className="banner"><ImageBox value={data.profile.banner} onChange={v=>update(d=>{d.profile.banner=v;return d})}/></div><main><header><ImageBox round value={data.profile.avatar} onChange={v=>update(d=>{d.profile.avatar=v;return d})}/><div className="identity"><div className="name"><h1>{data.profile.name}</h1><button className={edit?"active":""} onClick={()=>setEdit(!edit)}><Pencil size={13}/>{edit?"Concluir":"Editar perfil"}</button></div><div className="meta">@{data.profile.handle} · <MapPin size={13}/>{data.profile.location}</div><p>{data.profile.bio}</p></div></header><div className="saved"><Check size={12}/> Salvo neste navegador</div>
{data.sections.map((s,si)=><section key={s.id}><div className="sectionhead"><h2>{s.title}</h2>{edit&&<div><button onClick={()=>update(d=>{d.sections.splice(si,1);return d})}><Trash2 size={14}/></button></div>}</div>{s.type==="cards"&&<div className="grid">{s.items.map(i=><article key={i.id}><ImageBox value={i.image} onChange={v=>update(d=>{const x=d.sections.find(x=>x.id===s.id).items.find(x=>x.id===i.id);x.image=v;return d})}/><small>{i.tag}</small><h3>{i.title}</h3><p>{i.detail}</p>{edit&&<button className="remove" onClick={()=>update(d=>{const x=d.sections.find(x=>x.id===s.id);x.items=x.items.filter(x=>x.id!==i.id);return d})}><X size={13}/></button>}</article>)}{edit&&<button className="add" onClick={()=>update(d=>{d.sections.find(x=>x.id===s.id).items.push({id:uid(),tag:"Categoria",title:"Novo item",detail:"Detalhes",image:""});return d})}><Plus/> Adicionar item</button>}</div>}
{s.type==="settings"&&<div className="settings"><div className="tabs">{s.games.map(g=><button className={s.active===g?"sel":""} key={g} onClick={()=>update(d=>{d.sections.find(x=>x.id===s.id).active=g;return d})}>{g}</button>)}{edit&&<button onClick={()=>update(d=>{const x=d.sections.find(x=>x.id===s.id);const g="Novo jogo";x.games.push(g);x.rows[g]=[];x.active=g;return d})}><Plus size={13}/> Jogo</button>}</div>{s.active&&<div className="table">{(s.rows[s.active]||[]).map((r,ri)=><div className="row" key={ri}><span>{r[0]}</span><b>{r[1]}</b>{edit&&<button onClick={()=>update(d=>{d.sections.find(x=>x.id===s.id).rows[s.active].splice(ri,1);return d})}><X size={13}/></button>}</div>)}{edit&&<button className="addrow" onClick={()=>update(d=>{d.sections.find(x=>x.id===s.id).rows[s.active].push(["Configuração","Valor"]);return d})}><Plus size={13}/> Adicionar configuração</button>}</div>}</div>}
{s.type==="links"&&<div className="links">{s.items.map(i=><a key={i.id} href={i.url} target="_blank" rel="noreferrer"><LinkIcon size={13}/>{i.label}</a>)}</div>}
{s.type==="text"&&<div className="textblocks">{s.items.map(i=><article key={i.id}><h3>{i.title}</h3><p>{i.content}</p></article>)}</div>}</section>)}
{edit&&<div className="addsection">{!picker?<button onClick={()=>setPicker(true)}><Plus size={15}/> Adicionar seção</button>:<div className="picker">{[["cards","Cards",LayoutGrid],["settings","Configurações",Sliders],["links","Links",Share2],["text","Texto",Blocks]].map(([t,l,I])=><button key={t} onClick={()=>{addSection(t);setPicker(false)}}><I size={17}/>{l}</button>)}<button onClick={()=>setPicker(false)}><X size={14}/></button></div>}</div>}<footer><LinkIcon size={12}/>seusite.gg/{data.profile.handle}</footer></main></div>}
export default App;
